services:
  backend:
    container_name: ${APP_NAME}_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend/database:/app/database
      - ./backend/logs:/app/logs
      - /mnt/backups:/app/backups
    env_file:
      - .env
    environment:
      - TZ=Europe/Paris
    command: ["python", "run.py"]
    ports:
      - "${PORT_BACK}:${PORT_BACK}"
    networks:
      - badarts

  frontend:
    container_name: ${APP_NAME}_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
          VITE_APP_NAME: ${APP_NAME}
          VITE_PORT_BACK: ${PORT_BACK}
          VITE_ENV: ${ENV}
    restart: always
    env_file:
      - .env
    volumes:
      - /var/log/nginx:/var/log/nginx
    ports:
      - "${PORT_FRONT}:8081"
    networks:
      - badarts

networks:
  badarts:
    driver: bridge