services:
  backend:
    container_name: ${APP_NAME}_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend/database:/app/database
      - ./backend/logs:/app/logs
      - ./backend/backups:/app/backups
      - ./backend/leaderboards:/app/leaderboards
    env_file:
      - .env
    environment:
      - TZ=Europe/Paris
    command: ["python", "run.py"]
    networks:
      - badarts
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-badarts.rule=Host(`api.badarts.fr`)"
      - "traefik.http.routers.api-badarts.entrypoints=websecure"
      - "traefik.http.routers.api-badarts.tls=true"
      - "traefik.http.routers.api-badarts.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api-badarts-http.rule=Host(`api.badarts.fr`)"
      - "traefik.http.routers.api-badarts-http.entrypoints=web"
      - "traefik.http.routers.api-badarts-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.api-badarts.loadbalancer.server.port=${PORT_BACK}"

  frontend:
    container_name: ${APP_NAME}_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
          VITE_APP_NAME: ${APP_NAME}
          VITE_PORT_BACK: ${PORT_BACK}
          VITE_ENV: ${ENV}
          VITE_PRINTFUL: ${PRINTFUL}
    restart: always
    env_file:
      - .env
    volumes:
      - /var/log/nginx:/var/log/nginx
    environment:
      - TZ=Europe/Paris
    ports:
      - "${PORT_FRONT}:8081"
    networks:
      - badarts
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tournois-badarts.rule=Host(`badarts.fr`) || Host(`www.badarts.fr`)"
      - "traefik.http.routers.tournois-badarts.entrypoints=websecure"
      - "traefik.http.routers.tournois-badarts.tls=true"
      - "traefik.http.routers.tournois-badarts.tls.certresolver=letsencrypt"
      - "traefik.http.routers.tournois-badarts-http.rule=Host(`badarts.fr`) || Host(`www.badarts.fr`)"
      - "traefik.http.routers.tournois-badarts-http.entrypoints=web"
      - "traefik.http.routers.tournois-badarts-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.tournois-badarts.loadbalancer.server.port=8081"

networks:
  badarts:
    driver: bridge
  proxy:
    external: true